# Generated by Django 5.1.2 on 2024-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
